spring.application.name=chatBot-service
server.port=8090

spring.ai.openai.api-key=
spring.ai.openai.chat.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.model=nvidia/nemotron-3-ultra-550b-a55b:free


spring.cloud.discovery.enabled=false
spring.cloud.config.enabled=false

spring.ai.mcp.client.streamable-http.connections.customerServer.url=http://localhost:8081/mcp
spring.ai.mcp.client.streamable-http.connections.bankServer.url=http://localhost:8082/mcp

telegram.api.token=8513854044:AAG9iCKSrfHysreE6DpOmE9axPj7JWRse-s
