spring.application.name=chatBot-service
server.port=8090

spring.ai.openai.api-key=
spring.ai.openai.chat.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=llama-3.3-70b-versatile

spring.cloud.discovery.enabled=false
spring.cloud.config.enabled=false

