spring.application.name=ebank-service
server.port=8082
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:ebankdb

spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=true

spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.name=ebank-mcp
spring.ai.mcp.server.version=1.0.0
